name: Packer CI Test

on:
  pull_request:
    branches:
      - main

jobs:
  packer-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Packer
        run: |
          wget https://releases.hashicorp.com/packer/1.10.1/packer_1.10.1_linux_amd64.zip
          unzip packer_1.10.1_linux_amd64.zip
          sudo mv packer /usr/local/bin/

      - name: Run Packer Format Check
        run: |
          packer fmt -check -diff aws-packer.pkr.hcl

      - name: Run Packer Validate
        run: |
          packer validate aws-packer.pkr.hcl
