name: Packer CI Test

on:
  pull_request:
    branches:
      - main

jobs:
  packer-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Packer
        run: |
          wget https://releases.hashicorp.com/packer/1.10.1/packer_1.10.1_linux_amd64.zip
          unzip packer_1.10.1_linux_amd64.zip
          sudo mv packer /usr/local/bin/

      - name: Install Packer Plugins
        run: |
          packer plugins install github.com/hashicorp/amazon
          packer plugins install github.com/hashicorp/googlecompute

      - name: Install Google Cloud SDK
        run: |
          curl -sSL https://sdk.cloud.google.com | bash
          echo "✅ Google Cloud SDK Installed"

      - name: Authenticate to GCP
        run: |
          echo '${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}' > gcp-key.json
          gcloud auth activate-service-account --key-file=gcp-key.json
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

      - name: Create Dummy `webapp.zip`
        run: |
          zip -r webapp.zip ./
          ls -al

      - name: Run Packer Format Check
        run: |
          packer fmt -check -diff aws-packer.pkr.hcl

      - name: Run Packer init
        run: |
           packer init aws-packer.pkr.hcl

      - name: Run Packer Validate
        run: |
          echo '${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}' > gcp-key.json
          packer validate -var "db_user=${{ secrets.DB_USER }}" \
                          -var "db_name=${{ secrets.DB_NAME }}" \
                          -var "db_password=${{ secrets.DB_PASSWORD }}" \
                          -var "gcp_project_id=${{ secrets.GCP_PROJECT_ID }}" \
                          -var "gcp_account_file=gcp-key.json" \
                          -var "ssh_username=ubuntu" \
                          aws-packer.pkr.hcl
