name: Web App CI

on:
  pull_request:
    branches:
      - main  # Runs tests on PRs to main branch

jobs:
  test:
    name: Run Web App Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"  # Adjust Python version as needed

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pytest  # Install dependencies for tests

      - name: Run Tests
        run: pytest -v app/tests/test_api.py  # Run application tests
